before:
  hooks:
    - go mod download

builds:
  - id: git-get
    main: ./cmd/get/main.go
    binary: git-get
    ldflags:
      - -s -w 
      - -X git-get/pkg/cfg.version={{.Version}} 
      - -X git-get/pkg/cfg.commit={{.Commit}} 
      - -X git-get/pkg/cfg.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
  - id: git-list
    main: ./cmd/list/main.go
    binary: git-list
    ldflags:
      - -s -w 
      - -X git-get/pkg/cfg.version={{.Version}} 
      - -X git-get/pkg/cfg.commit={{.Commit}} 
      - -X git-get/pkg/cfg.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows

archives:
  - id: archive
    builds:
      - git-get
      - git-list
    format_overrides:
      - goos: windows
        format: zip
    # Don't include any additional files into the archives (such as README, CHANGELOG etc). 
    files:
      - none* 

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

release:
  github:
    owner: rupor-github
    name: git-get

brews:
  - name: git-get
    repository:
      owner: grdl
      name: homebrew-tap
    commit_author:
      name: Grzegorz Dlugoszewski
      email: git-get@grdl.dev
    directory: Formula
    homepage: https://github.com/grdl/git-get/
    description: Better way to clone, organize and manage multiple git repositories
    test: |
      system "git-get --version"
    install: |
      bin.install "git-get", "git-list"

nfpms:
  - license: MIT
    maintainer: grdl
    homepage: https://github.com/grdl/git-get
    bindir: /usr/local/bin
    dependencies:
      - git
    description: Better way to clone, organize and manage multiple git repositories
    formats:
      - deb
      - rpm
